/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./../packages/ui/src/AppMain.vue')['default']
    Gallery: typeof import('./../packages/ui/src/Gallery.vue')['default']
    ImgViewer: typeof import('./../packages/ui/src/ImgViewer.vue')['default']
    MainHeader: typeof import('./../packages/ui/src/MainHeader.vue')['default']
    MainImage: typeof import('./../packages/ui/src/MainImage.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NUpload: typeof import('naive-ui')['NUpload']
    PostAction: typeof import('./../packages/ui/src/post/Action.vue')['default']
    PostCard: typeof import('./../packages/ui/src/post/Card.vue')['default']
    PostComments: typeof import('./../packages/ui/src/post/Comments.vue')['default']
    PostItem: typeof import('./../packages/ui/src/post/Item.vue')['default']
    PostList: typeof import('./../packages/ui/src/post/List.vue')['default']
    PostMeta: typeof import('./../packages/ui/src/post/Meta.vue')['default']
    PostPagination: typeof import('./../packages/ui/src/post/Pagination.vue')['default']
    PostRetweeted: typeof import('./../packages/ui/src/post/Retweeted.vue')['default']
    PostText: typeof import('./../packages/ui/src/post/Text.vue')['default']
    Preview: typeof import('./../packages/ui/src/Preview.vue')['default']
    Profile: typeof import('./../packages/ui/src/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsAbout: typeof import('./../packages/ui/src/settings/about.vue')['default']
    SettingsBase: typeof import('./../packages/ui/src/settings/base.vue')['default']
    SettingsDesktop: typeof import('./../packages/ui/src/settings/desktop.vue')['default']
    SettingsWeb: typeof import('./../packages/ui/src/settings/web.vue')['default']
    Theme: typeof import('./../packages/ui/src/Theme.vue')['default']
  }
}
