/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./../packages/ui/src/AppMain.vue')['default']
    Dark: typeof import('./../packages/ui/src/Dark.vue')['default']
    File: typeof import('./../apps/desktop/renderer/src/components/File.vue')['default']
    Gallery: typeof import('./../packages/ui/src/Gallery.vue')['default']
    ImgViewer: typeof import('./../packages/ui/src/ImgViewer.vue')['default']
    MainHeader: typeof import('./../packages/ui/src/MainHeader.vue')['default']
    MainImage: typeof import('./../packages/ui/src/MainImage.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NImage: typeof import('naive-ui')['NImage']
    NImageGroup: typeof import('naive-ui')['NImageGroup']
    NInput: typeof import('naive-ui')['NInput']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NSwitch: typeof import('naive-ui')['NSwitch']
    PostAction: typeof import('./../packages/ui/src/post/Action.vue')['default']
    PostCard: typeof import('./../packages/ui/src/post/Card.vue')['default']
    PostComments: typeof import('./../packages/ui/src/post/Comments.vue')['default']
    PostItem: typeof import('./../packages/ui/src/post/Item.vue')['default']
    PostList: typeof import('./../packages/ui/src/post/List.vue')['default']
    PostMeta: typeof import('./../packages/ui/src/post/Meta.vue')['default']
    PostPagination: typeof import('./../packages/ui/src/post/Pagination.vue')['default']
    PostRetweeted: typeof import('./../packages/ui/src/post/Retweeted.vue')['default']
    PostText: typeof import('./../packages/ui/src/post/Text.vue')['default']
    Preview: typeof import('./../packages/ui/src/Preview.vue')['default']
    Profile: typeof import('./../packages/ui/src/Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDesktop: typeof import('./../packages/ui/src/settings/desktop.vue')['default']
    SettingsWeb: typeof import('./../packages/ui/src/settings/web.vue')['default']
    Sqlite: typeof import('./../apps/desktop/renderer/src/components/Sqlite.vue')['default']
  }
}
