/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppMain: typeof import('./AppMain.vue')['default']
    Config: typeof import('./Config.vue')['default']
    Ctrl: typeof import('./Ctrl.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    Gallery: typeof import('./Gallery.vue')['default']
    ImgViewer: typeof import('./ImgViewer.vue')['default']
    PostAction: typeof import('./post/Action.vue')['default']
    PostCard: typeof import('./post/Card.vue')['default']
    PostComments: typeof import('./post/Comments.vue')['default']
    PostItem: typeof import('./post/Item.vue')['default']
    PostList: typeof import('./post/List.vue')['default']
    PostMeta: typeof import('./post/Meta.vue')['default']
    PostRetweeted: typeof import('./post/Retweeted.vue')['default']
    PostText: typeof import('./post/Text.vue')['default']
    Preview: typeof import('./Preview.vue')['default']
    Profile: typeof import('./Profile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiHeader: typeof import('./ui/Header.vue')['default']
  }
}
