import { z } from 'zod'

const RawUserInfoSchema = z.object({
  user: z.object({
    id: z.number(),
    idstr: z.string(),
    pc_new: z.number(),
    screen_name: z.string(),
    profile_image_url: z.string(),
    profile_url: z.string(),
    verified: z.boolean(),
    verified_type: z.number(),
    domain: z.string(),
    weihao: z.string(),
    verified_type_ext: z.number(),
    status_total_counter: z.object({
      total_cnt_format: z.string(),
      comment_cnt: z.string(),
      repost_cnt: z.string(),
      like_cnt: z.string(),
      total_cnt: z.string(),
    }),
    avatar_large: z.string(),
    avatar_hd: z.string(),
    follow_me: z.boolean(),
    following: z.boolean(),
    mbrank: z.number(),
    mbtype: z.number(),
    v_plus: z.number(),
    user_ability: z.number(),
    planet_video: z.boolean(),
    verified_reason: z.string(),
    description: z.string(),
    location: z.string(),
    gender: z.string(),
    followers_count: z.number(),
    followers_count_str: z.string(),
    friends_count: z.number(),
    statuses_count: z.number(),
    url: z.string(),
    svip: z.number(),
    vvip: z.number(),
    cover_image_phone: z.string(),
    icon_list: z.array(
      z.object({
        type: z.string(),
        data: z.object({
          mbrank: z.number(),
          mbtype: z.number(),
          svip: z.number(),
          vvip: z.number(),
        }),
      }),
    ),
    top_user: z.number(),
    user_type: z.number(),
    is_star: z.string(),
    is_muteuser: z.boolean(),
    special_follow: z.boolean(),
  }),
  tabList: z.array(z.object({ name: z.string(), tabName: z.string() })),
  blockText: z.string(),
})

export type RawUserInfo = z.infer<typeof RawUserInfoSchema>
